# Generated by Django 3.0.5 on 2020-05-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
