# Generated by Django 3.0.5 on 2020-05-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200517_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='status',
        ),
    ]
