# Generated by Django 3.0.5 on 2020-05-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20200517_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='status',
        ),
    ]
