# Generated by Django 3.0.5 on 2020-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_remove_resource_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
